repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks
        name: "ðŸ”’ security Â· Detect hardcoded secrets"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.1
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]

  # To make sure your uv.lock file is up to date even if your pyproject.toml file was changed via pre-commit
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.8
    hooks:
      - id: uv-lock
  # To keep your requirements.txt file updated using pre-commit:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.8
    hooks:
      - id: uv-export
